# Generated by Django 4.1.13 on 2024-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
    ]
