# Generated by Django 4.1.13 on 2024-06-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('robots', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, max_length=70, null=True)),
                ('og_description', models.CharField(blank=True, max_length=160, null=True)),
                ('og_image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
